### ISSUE TITLE
issue with foreign providers

### ISSUE THREAD

**Issue by Safi-hammoud** [stremify/stremify#19]
Hi ,,speaking about the selfhosted version via Vercel ,, the foreign providers are all down (dont show results- movies or series) except for the french provider which still working good .. this happened since 2 days

could you please offer a fix ?

**Comment by infvortx** [comment]
I'll look into it.

**Comment by Safi-hammoud** [comment]
The foreign providers are all back to work like charm today 
Big thx to you 
Please don't give stremify up .. it's one of the best addons for stremio
