### ISSUE TITLE
Deprecated Library , Deploy fails on Vercel

### ISSUE THREAD

**Issue by UrloMythus** [stremify/stremify#21]
Hello, recently I have tried to Re-deploy again stremify on vercel but it failed. Even by creating a brand-new repo and a brand new vercel project, the build still fails. 
The error is caused by a deprecated library(vm). Here the full logs. Thanks in advance if you can fix this. 
``
Running "vercel build"
Vercel CLI 34.1.8
Installing dependencies...
npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@movie-web/providers/-/providers-2.2.2.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@movie-web/providers@https://registry.npmjs.org/@movie-web/providers/-/providers-2.2.2.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in: /vercel/.npm/_logs/2024-05-03T21_07_00_297Z-debug-0.log
Error: Command "npm install" exited with 1
``

**Comment by infvortx** [comment]
You need to switch where @movie-web/providers is sourced from or wait for v2.7 to release. You can switch the source to:
    "@movie-web/providers": "sussy-code/providers",
