### ISSUE TITLE
web-providers

### ISSUE THREAD

**Issue by Safi-hammoud** [stremify/stremify#22]
Hi ,, 
The Addon is down via Vercel  :(
It seems to be issue with the web-provider dependency .. which was taken down 
could you please fix it ?
Stremify is cool and it would be sad to let it down  ,, since it is the Addon on Stremio that offers German Providers ...

Thank you ... :)

**Comment by infvortx** [comment]
You need to switch where @movie-web/providers is sourced from or wait for v2.7 to release. You can switch the source to:
"@movie-web/providers": "sussy-code/providers",
