### ISSUE TITLE
Eurostreaming wrong domain

### ISSUE THREAD

**Issue by UrloMythus** [stremify/stremify#25]
Hello, I have just noticed you have changed the domain of eurostreaming.forum to eurostreaming.money.  Altought this is wrong because they are two completely different websites. 
The correct address is eurostreaming.casino . The eurostreaming you are using is basically a copy of guardaserie.ceo
Eurostreaming.money (the real eurostreaming site) uses other video players (Deltabit,maxstream,mixdrop). 
Thanks in advance, and thanks again for your great work. 

P.S. I thought it was better to create a new issue for that since in the other's one you could miss the message since you have put it in the label of things to do. Anyway, point me in the right direction if you think I should continue the other thread instead of creating a new one.

**Comment by infvortx** [comment]
Fixed. 👍
