### ISSUE TITLE
Keys and smashybase Changed

### ISSUE THREAD

**Issue by 0x86e3x4** [stremify/stremify#31]
smashystreamBase 
 : atob('aHR0cHM6Ly9lbWJlZC5zbWFzaHlzdHJlYW0uY29tLw==') // https://embed.smashystream.com/
now changed to https://smashystream.top 
keys : -------

**Comment by infvortx** [comment]
I’ll look into it, but chances are I’d likely just drop Smashystream atp cause it requires a fix way too often.

**Comment by 0x86e3x4** [comment]
you can create a decrypt instance to update keys automatically

**Comment by infvortx** [comment]
There was an automatic decryptor but it got broken due to Smashystream changing the way their player works.

**Comment by infvortx** [comment]
Won't fix for now.
