### ISSUE TITLE
pnpm run start returns an error

### ISSUE THREAD

**Issue by Impure2411** [stremify/stremify#38]
Hello,

Since [Elfhosted](https://stremify.elfhosted.com/) does not work, I tried to host my own with the help of wiki, but got stuck in running stremify part.

When I run `pnpm run start`, it returns an error message below.
`ERR_PNPM_NO_SCRIPT_OR_SERVER  Missing script start or file server.js`

I tried to modify package.json file and add "start": but am not sure what to add (nitro.config.ts?). Could you give me a pointer?

Thanks!

**Comment by infvortx** [comment]
Ah, there was a mistake in the documentation.

It is supposed to be ``pnpm run dev``.

**Comment by Impure2411** [comment]
Thank you! It works fine now. It would be helpful if you can update the doc at some point :)
