### ISSUE TITLE
Wrong Result for All series, Eurostreaming

### ISSUE THREAD

**Issue by vitouchiha** [stremify/stremify#40]
Hello, I just wanted to report that Stremify finds the wrong result for all series TV 

Instead of the episode, it finds an episode of Emily in Paris.

**Comment by infvortx** [comment]
Are you selfhosting?

**Comment by UrloMythus** [comment]
I just tried as well, on the public elfhosted instance, and I can confirm the bug has not been fixed or the fix pushed.

**Comment by vitouchiha** [comment]
> Are you selfhosting?

I'm using the public instance

**Comment by infvortx** [comment]
Should be fixed now.
